reorder: commit to update after sync and updateBaseImages.sh since --nocommit flag doesn't seem to work (x4 more)
Change-Id: I8f75cfe6280b8e1cbe28f76211bea4396c584717
Signed-off-by: nickboldt <nboldt@redhat.com>

diff --git a/dependencies/kubernetes-image-puller/Jenkinsfile b/dependencies/kubernetes-image-puller/Jenkinsfile
--- a/dependencies/kubernetes-image-puller/Jenkinsfile
+++ b/dependencies/kubernetes-image-puller/Jenkinsfile
@@ -81,7 +81,7 @@ cd ${WORKSPACE}/sources
 
   # can't yet generate a PR against eclipse/che-* repos, and can't push directly
   # so check for a new base image but DO NOT commit/push/pull-request
-  /tmp/updateBaseImages.sh -b ''' + SOURCE_BRANCH + ''' -f ${SOURCEDOCKERFILE##*/} --nocommit
+	/tmp/updateBaseImages.sh -b ''' + SOURCE_BRANCH + ''' -f ${SOURCEDOCKERFILE##*/} --nocommit
 
   # TEST CHANGES
   # TODO move this out of bootstrap string so we don't add the same testchanges string 3 times
@@ -177,11 +177,10 @@ cd ${WORKSPACE}/target
 if [[ \$(git diff --name-only) ]]; then # file changed
 	OLD_SHA=\$(git rev-parse HEAD) # echo ${OLD_SHA:0:8}
 	git add Dockerfile ${SYNC_FILES}
-  /tmp/updateBaseImages.sh -b ''' + GIT_BRANCH + ''' --nocommit
-  git diff --cached
-  # note this might fail if we're syncing from a tag vs. a branch
+	# note this might fail if we're syncing from a tag vs. a branch
 	git commit -s -m "[sync] Update from ''' + SOURCE_REPO + ''' @ ${SOURCE_SHA:0:8}" Dockerfile ${SYNC_FILES}
-	git push origin ''' + GIT_BRANCH + '''
+	/tmp/updateBaseImages.sh -b ''' + GIT_BRANCH + ''' --nocommit
+	git push origin ''' + GIT_BRANCH + ''' || true
 	NEW_SHA=\$(git rev-parse HEAD) # echo ${NEW_SHA:0:8}
 	if [[ "${OLD_SHA}" != "${NEW_SHA}" ]]; then hasChanged=1; fi
 	echo "[sync] Updated pkgs.devel @ ${NEW_SHA:0:8} from ''' + SOURCE_REPO + ''' @ ${SOURCE_SHA:0:8}"
